USE [master]
GO

/****** Object:  Database [StockTest]    Script Date: 5/10/2021 13:20:22 ******/
CREATE DATABASE [StockTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StockTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.EXERCISES\MSSQL\DATA\StockTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StockTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.EXERCISES\MSSQL\DATA\StockTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StockTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StockTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StockTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StockTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StockTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StockTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [StockTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StockTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StockTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StockTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StockTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StockTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StockTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StockTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StockTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StockTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StockTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StockTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StockTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StockTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StockTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StockTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StockTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StockTest] SET RECOVERY FULL 
GO

ALTER DATABASE [StockTest] SET  MULTI_USER 
GO

ALTER DATABASE [StockTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StockTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StockTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StockTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StockTest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StockTest] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [StockTest] SET QUERY_STORE = OFF
GO

ALTER DATABASE [StockTest] SET  READ_WRITE 
GO


